name = "MyExamplePack"
uuid = "e1458960-ad58-451c-bc2e-4c3ad3f82c74"
authors = ["Vidhyarth T S"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
